site_name: { { cookiecutter.package_name } }
repo_url: https://github.com/imanousar/{{cookiecutter.package_name}}
site_url: https://imanousar.github.io/{{cookiecutter.package_name}}/
site_description: description
site_author: Giannis Manousaridis
use_directory_urls: false

theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link

plugins:
  - search

nav:
  - Home: index.md
